name: Dev Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install
        run: npm i

      - name: build
        run: npm run build

      - name: publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN\nregistry=https://registry.npmjs.org/" >> .npmrc
          npm version $(node --eval="process.stdout.write(require('./package.json').version)")-dev.$(git rev-parse --short HEAD) --no-git-tag-version
          npm publish --userconfig ./.npmrc --provenance --access public --no-git-tag-version --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
